# Generated by Django 3.0.8 on 2020-09-16 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GraphDatas',
        ),
    ]
