# Generated by Django 3.0.8 on 2020-09-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mydashboard', '0002_delete_graphdatas'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date de revelé des données')),
                ('nb_owners', models.PositiveSmallIntegerField(verbose_name='nombre de proprios devant stériliser un animal')),
                ('nb_contacted', models.PositiveSmallIntegerField(verbose_name='nombre de proprios déjà contacté')),
                ('nb_to_contact', models.PositiveSmallIntegerField(verbose_name='nombre de proprios à contacter')),
            ],
        ),
    ]
