# Generated by Django 3.0.8 on 2020-09-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydashboard', '0003_gramodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gramodel',
            name='date',
            field=models.DateField(verbose_name='date de revelé des données'),
        ),
    ]
