# Generated by Django 3.0.8 on 2020-07-03 08:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminData',
            fields=[
                ('admin_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.IntegerField(unique=True)),
                ('chip', models.IntegerField(unique=True)),
                ('tatoo', models.IntegerField(unique=True)),
                ('is_neutered', models.BooleanField(default=False)),
                ('can_be_neutered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du contact')),
                ('resume', models.CharField(blank=True, max_length=90)),
                ('full_text', models.TextField(blank=True)),
                ('is_mail', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('animal_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('telephone', models.IntegerField(unique=True)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('nb_mail_send', models.SmallIntegerField(default=0)),
                ('nb_call', models.SmallIntegerField(default=0)),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheet.Contact', verbose_name='contact')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('animal_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateTimeField(verbose_name='Date de naissance')),
                ('race', models.CharField(max_length=50)),
                ('is_cat', models.BooleanField(default=True)),
                ('color', models.CharField(max_length=30)),
                ('is_male', models.BooleanField(default=True)),
                ('date_of_adoption', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'adoption")),
                ('admin_data_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sheet.AdminData')),
                ('owner_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sheet.Owner')),
            ],
        ),
    ]
