# Generated by Django 3.1.1 on 2021-01-13 12:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.CharField(blank=True, max_length=15, null=True, verbose_name='Numéro de dossier')),
                ('chip', models.CharField(blank=True, max_length=15, null=True, verbose_name='Numéro de puce')),
                ('tatoo', models.CharField(blank=True, max_length=15, null=True, verbose_name='Numéro de tatouage')),
                ('is_neutered', models.CharField(default=0, max_length=1, verbose_name='statut stérilisation (stérile, stérilisable, à stériliser)')),
                ('date_of_neuter', models.DateField(blank=True, null=True, verbose_name='A été stérilisé(e) le')),
                ('futur_date_of_neuter', models.DateField(blank=True, null=True, verbose_name='Sera stérilisable le')),
                ('status', models.TextField(blank=True, max_length=200, null=True, verbose_name='Explication concernant la stérilisation')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=50, null=True, verbose_name='Prénom propriétaire')),
                ('owner_surname', models.CharField(max_length=50, null=True, verbose_name='Nom propriétaire')),
                ('owner_sex', models.CharField(default=0, max_length=1, null=True, verbose_name='Sexe propriétaire\n (0 = H / 1 = F)')),
                ('phone', models.CharField(max_length=30, unique=True, verbose_name='Téléphone')),
                ('mail', models.EmailField(max_length=254, unique=True, verbose_name='Mail')),
                ('tel_reminder', models.CharField(default=0, max_length=3, verbose_name="Nombre d'appel passés")),
                ('mail_reminder', models.CharField(default=0, max_length=3, verbose_name='Nombre de mail envoyés')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date du contact')),
                ('resume', models.CharField(default='A compléter ...', max_length=90)),
                ('full_text', models.TextField(default='A compléter ...')),
                ('nature', models.CharField(default='à compléter', max_length=1)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sheet.owner', verbose_name='Gestion des contacts')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Nom')),
                ('date_of_birth', models.DateField(verbose_name='Date de naissance')),
                ('race', models.CharField(max_length=50)),
                ('species', models.CharField(max_length=1, verbose_name='chat/chatte/chien/chienne')),
                ('color', models.CharField(blank=True, max_length=30, verbose_name='Couleur')),
                ('date_of_adoption', models.DateField(verbose_name="Date d'adoption")),
                ('observation', models.CharField(blank=True, max_length=50)),
                ('caution', models.CharField(max_length=5, verbose_name='Montant de la caution(sans €)')),
                ('nature_caution', models.CharField(default='chèque', max_length=20, verbose_name='Nature de la caution(sans €)')),
                ('picture', models.FileField(blank=True, default='animals/no-img.j', null=True, upload_to='animals/')),
                ('admin_data', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sheet.admindata', verbose_name='Suivi administratif')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sheet.owner', verbose_name='Propriétaire')),
            ],
        ),
    ]
