# Generated by Django 3.0.8 on 2020-07-13 09:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminData',
            fields=[
                ('file', models.IntegerField(blank=True, null=True, verbose_name='Numéro de dossier')),
                ('chip', models.IntegerField(blank=True, null=True, verbose_name='Numéro de puce')),
                ('tatoo', models.IntegerField(blank=True, null=True, verbose_name='Numéro de tatouage')),
                ('is_neutered', models.BooleanField(default=False, verbose_name='Stérilisé')),
                ('date_of_neuter', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date de stérilisation')),
                ('status', models.TextField(blank=True, max_length=200, null=True, verbose_name='Explication concernant la stérilisation')),
                ('admin_data_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date du contact')),
                ('resume', models.CharField(blank=True, max_length=90)),
                ('full_text', models.TextField(blank=True)),
                ('is_mail', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50, null=True, verbose_name='Idt du proprio')),
                ('telephone', models.CharField(max_length=30, unique=True, verbose_name='Téléphone')),
                ('mail', models.EmailField(max_length=254, unique=True, verbose_name='Mail')),
                ('tel_reminder', models.SmallIntegerField(default=0, verbose_name="Nombre d'appel passés")),
                ('mail_reminder', models.SmallIntegerField(default=0, verbose_name='Nombre de mail envoyés')),
                ('caution', models.CharField(default='null', max_length=30, null=True, verbose_name='Caution + support (ex : 200e en chèque)')),
                ('contact_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sheet.Contact', verbose_name='Gestion des contacts')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('animal_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Nom')),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now, verbose_name='Date de naissance')),
                ('race', models.CharField(max_length=50)),
                ('species', models.CharField(default='chat', max_length=7, verbose_name='chat/chatte/chien/chienne')),
                ('color', models.CharField(blank=True, max_length=30, verbose_name='Couleur')),
                ('date_of_adoption', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'adoption")),
                ('picture', models.FileField(blank=True, default='animals/no-img.j', null=True, upload_to='animals/')),
                ('admin_data_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sheet.AdminData', verbose_name='Suivi administratif')),
                ('owner_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sheet.Owner', verbose_name='Propriétaire')),
            ],
        ),
    ]
