# Generated by Django 3.0.8 on 2020-07-13 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='telephone',
            new_name='phone',
        ),
    ]
