# Generated by Django 3.1.1 on 2020-09-30 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owner_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner_sex',
            new_name='sex',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner_surname',
            new_name='surname',
        ),
    ]
