# Generated by Django 3.0.8 on 2020-07-03 08:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='date_of_adoption',
            field=models.DateField(default=django.utils.timezone.now, verbose_name="Date d'adoption"),
        ),
        migrations.AlterField(
            model_name='animal',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date du contact'),
        ),
    ]
