# Generated by Django 3.0.8 on 2020-07-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0002_auto_20200703_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindata',
            name='chip',
            field=models.IntegerField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='admindata',
            name='file',
            field=models.IntegerField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='admindata',
            name='tatoo',
            field=models.IntegerField(blank=True, unique=True),
        ),
    ]
