# Generated by Django 3.0.8 on 2020-07-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0002_auto_20200713_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindata',
            name='chip',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Numéro de puce'),
        ),
        migrations.AlterField(
            model_name='admindata',
            name='file',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Numéro de dossier'),
        ),
        migrations.AlterField(
            model_name='admindata',
            name='tatoo',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Numéro de tatouage'),
        ),
    ]
