# Generated by Django 3.0.8 on 2020-07-03 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0004_auto_20200703_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindata',
            name='can_be_neutered',
            field=models.BooleanField(default=False, verbose_name='Doit être stérilisé'),
        ),
        migrations.AlterField(
            model_name='admindata',
            name='chip',
            field=models.IntegerField(blank=True, default=0, unique=True, verbose_name='Numéro de puce'),
        ),
        migrations.AlterField(
            model_name='admindata',
            name='file',
            field=models.IntegerField(blank=True, default=0, unique=True, verbose_name='Numéro de dossier'),
        ),
        migrations.AlterField(
            model_name='admindata',
            name='is_neutered',
            field=models.BooleanField(default=False, verbose_name='Stérilisé'),
        ),
        migrations.AlterField(
            model_name='admindata',
            name='tatoo',
            field=models.IntegerField(blank=True, default=0, unique=True, verbose_name='Numéro de tatouage'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='is_cat',
            field=models.BooleanField(default=True, verbose_name="Espèce : Cocher si c'est un chat"),
        ),
        migrations.AlterField(
            model_name='animal',
            name='is_male',
            field=models.BooleanField(default=True, verbose_name="Sexe : Cocher si c'est un mâle"),
        ),
        migrations.AlterField(
            model_name='owner',
            name='contact_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sheet.Contact', verbose_name='Gestion des contacts'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='mail',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Mail'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='nb_call',
            field=models.SmallIntegerField(default=0, verbose_name="Nombre d'appel passés"),
        ),
        migrations.AlterField(
            model_name='owner',
            name='nb_mail_send',
            field=models.SmallIntegerField(default=0, verbose_name='Nombre de mail envoyés'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='surname',
            field=models.CharField(max_length=30, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='telephone',
            field=models.IntegerField(unique=True, verbose_name='Téléphone'),
        ),
    ]
