# Generated by Django 3.0.8 on 2020-07-13 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0004_auto_20200713_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='admin_data_id',
            new_name='admin_data',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
