# Generated by Django 3.0.8 on 2020-07-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0005_auto_20200713_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindata',
            name='date_of_neuter',
            field=models.DateField(blank=True, null=True, verbose_name='Date de stérilisation'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='date_of_adoption',
            field=models.DateTimeField(verbose_name="Date d'adoption"),
        ),
        migrations.AlterField(
            model_name='animal',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date de naissance'),
        ),
    ]
