# Generated by Django 3.0.8 on 2020-07-03 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('sheet', '0005_auto_20200703_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='animal_id',
            new_name='owner_id',
        ),
        migrations.AlterField(
            model_name='owner',
            name='contact_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sheet.Contact', verbose_name='Gestion des contacts'),
        ),
    ]
