# Generated by Django 3.0.8 on 2020-07-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0006_auto_20200714_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='date_of_adoption',
            field=models.DateField(verbose_name="Date d'adoption"),
        ),
    ]
