# Generated by Django 3.0.8 on 2020-07-03 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0006_auto_20200703_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='admin_data_id',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='owner_id',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='contact_id',
        ),
        migrations.DeleteModel(
            name='AdminData',
        ),
        migrations.DeleteModel(
            name='Animal',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
