# Generated by Django 3.0.8 on 2020-07-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0008_admindata_animal_contact_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindata',
            name='can_be_neutered',
            field=models.BooleanField(default=False, verbose_name='Peut être stérilisé'),
        ),
        migrations.AlterField(
            model_name='admindata',
            name='chip',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Numéro de puce'),
        ),
        migrations.AlterField(
            model_name='admindata',
            name='file',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Numéro de dossier'),
        ),
        migrations.AlterField(
            model_name='admindata',
            name='tatoo',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Numéro de tatouage'),
        ),
    ]
