# Generated by Django 3.0.8 on 2020-08-27 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0010_auto_20200827_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owner_surnname',
            new_name='owner_surname',
        ),
    ]
