# Generated by Django 3.0.8 on 2020-08-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0011_auto_20200827_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindata',
            name='futur_date_of_neuter',
            field=models.DateField(blank=True, null=True, verbose_name='Sera stérilisé(e) le'),
        ),
        migrations.AlterField(
            model_name='admindata',
            name='date_of_neuter',
            field=models.DateField(blank=True, null=True, verbose_name='A été stérilisé(e) le'),
        ),
    ]
