# Generated by Django 3.0.8 on 2020-08-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0012_auto_20200828_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindata',
            name='is_neutered',
            field=models.SmallIntegerField(default=0, verbose_name='statut stérilisation (stérile, stérilisable, sera stérilisable)'),
        ),
    ]
