# Generated by Django 3.0.8 on 2020-09-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0015_animal_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='species',
            field=models.SmallIntegerField(verbose_name='chat/chatte/chien/chienne'),
        ),
    ]
