# Generated by Django 3.0.8 on 2020-09-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0016_auto_20200903_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owner_sex',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Sexe propriétaire (H/F)'),
        ),
    ]
