# Generated by Django 3.0.8 on 2020-09-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0019_auto_20200916_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindata',
            name='is_neutered',
            field=models.CharField(default=0, max_length=1, verbose_name='statut stérilisation (stérile, stérilisable, à stériliser)'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='species',
            field=models.CharField(max_length=1, verbose_name='chat/chatte/chien/chienne'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner_sex',
            field=models.CharField(default=0, max_length=1, null=True, verbose_name='Sexe propriétaire\n (0 = H / 1 = F)'),
        ),
    ]
