# Generated by Django 3.0.8 on 2020-09-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0021_auto_20200917_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact_date',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='owner',
            name='need_contact',
            field=models.BooleanField(default=True, verbose_name="besoin d'être contacté(e)"),
        ),
    ]
