# Generated by Django 3.0.8 on 2020-09-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0022_auto_20200924_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='date',
            new_name='contact_date',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='is_mail',
        ),
        migrations.AddField(
            model_name='contact',
            name='nature',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='full_text',
            field=models.TextField(default='A compléter ...'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='resume',
            field=models.CharField(default='A compléter ...', max_length=90),
        ),
    ]
