# Generated by Django 3.0.8 on 2020-09-26 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0023_auto_20200924_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='need_contact',
        ),
        migrations.AddField(
            model_name='contact',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sheet.Owner', verbose_name='Gestion des contacts'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='nature',
            field=models.CharField(default='à compléter', max_length=20),
        ),
    ]
