# Generated by Django 3.0.8 on 2020-09-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0024_auto_20200926_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='caution',
        ),
        migrations.AddField(
            model_name='animal',
            name='caution',
            field=models.CharField(default='null', max_length=30, null=True, verbose_name='Caution + support (ex : 200e en chèque)'),
        ),
    ]
