# Generated by Django 3.0.8 on 2020-09-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0025_auto_20200926_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='nature_caution',
            field=models.CharField(default='chèque', max_length=20, verbose_name='Nature de la caution(sans €)'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='caution',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Montant de la caution(sans €)'),
        ),
    ]
