# Generated by Django 3.0.8 on 2020-09-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0026_auto_20200926_1048'),
    ]


    atomic = False

    operations = [
        migrations.RenameField(
            model_name='admindata',
            old_name='admin_data_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='animal_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='admindata',
            name='futur_date_of_neuter',
            field=models.DateField(blank=True, null=True, verbose_name='Sera stérilisable le'),
        ),
    ]
