# Generated by Django 3.0.8 on 2020-07-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('mail_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('resume', models.CharField(blank=True, max_length=120)),
                ('full_text', models.TextField(blank=True)),
            ],
        ),
    ]
