# Generated by Django 3.1.1 on 2020-10-04 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='full_text',
            new_name='plain_text',
        ),
    ]
