# Generated by Django 3.0.8 on 2020-07-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='send_after_creation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mail',
            name='send_after_modif',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mail',
            name='send_at_this_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mail',
            name='send_when_x_month',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
