# Generated by Django 3.0.8 on 2020-09-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_auto_20200720_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='send_after_creation',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='mail',
            name='send_after_modif',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
