# Generated by Django 3.1.1 on 2020-10-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_auto_20201004_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='send_after_delete',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
