# Generated by Django 3.0.8 on 2020-09-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_auto_20200903_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='auto_send',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
