# Generated by Django 3.0.8 on 2020-09-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_mail_auto_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
