# Generated by Django 3.1.1 on 2020-12-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_auto_20201012_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='send_after_creation',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='send_after_delete',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='send_after_modif',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='send_every_2_weeks',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='send_when_neuterable',
        ),
        migrations.AddField(
            model_name='mail',
            name='condition',
            field=models.IntegerField(blank=True, choices=[(1, 'Send After Creation'), (2, 'Send After Creation No Neuter'), (3, 'Send After Update Caution'), (4, 'Send After Delete'), (5, 'Send When Neuterable'), (6, 'Send Every 2 Weeks')], null=True),
        ),
    ]
