# Generated by Django 3.1.1 on 2020-12-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_auto_20201209_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='condition',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
