# Generated by Django 3.0.8 on 2020-09-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_auto_20200910_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='send_after_creation',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='mail',
            name='send_after_modif',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='mail',
            name='send_at_this_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
