# Generated by Django 3.0.8 on 2020-09-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0006_auto_20200910_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='send_after_creation',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='mail',
            name='send_after_modif',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
